# wrangler.toml
name = 'navigation'
main = "worker.js"
compatibility_date = "2025-11-21"
keep_vars = true

# 绑定 KV 命名空间
[[kv_namespaces]]
binding = "NAVIGATION_STORE"  # 在代码中使用的变量名
id = "56c3988bfe444ccc837e163c30817886"  # KV 命名空间的 ID